"""
Pen Plotter App — Flask backend.

Serves the static HTML app and exposes:
    /api/defaults  — default plot settings
    /api/plot      — SVG + settings → ZIP of per-layer .gcode files
    /api/preview   — SVG + settings → JSON of per-layer optimized polylines
                     (what the plot will actually draw, after vpype's
                     linemerge / linesort / linesimplify)

Run via start.ps1, or directly:
    .\\.venv\\Scripts\\python.exe server.py
"""

import io
import re
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

from flask import Flask, jsonify, request, send_file, send_from_directory
from flask_cors import CORS

ROOT = Path(__file__).resolve().parent
APP_DIR = ROOT / "app"
VPYPE_EXE = ROOT / ".venv" / "Scripts" / "vpype.exe"

app = Flask(__name__, static_folder=None)
CORS(app)


# ---------- defaults ----------

DEFAULT_SETTINGS = {
    "pen_up_z": 5.0,
    "pen_down_z": -1.0,
    "draw_feed": 2000,
    "z_feed": 1000,
    "tolerance_mm": 0.1,
}


# ---------- gwrite profile builders ----------

def render_gcode_profile(settings: dict) -> str:
    """gwrite profile producing the DDCS-flavored G-code (for /api/plot)."""
    up = float(settings.get("pen_up_z", DEFAULT_SETTINGS["pen_up_z"]))
    down = float(settings.get("pen_down_z", DEFAULT_SETTINGS["pen_down_z"]))
    draw_f = int(settings.get("draw_feed", DEFAULT_SETTINGS["draw_feed"]))
    z_f = int(settings.get("z_feed", DEFAULT_SETTINGS["z_feed"]))

    return f"""[gwrite.ddcs_runtime]
unit = "mm"
vertical_flip = true
info = "Pen plotter app runtime profile (DDCS Expert M350)."

document_start = \"\"\"(--- DDCS pen plotter program ---)
(Generated by pen plotter app)
G21 (mm)
G90 (absolute)
G17 (XY plane)
G94 (feed per min)
G1 Z{up:.3f} F{z_f} (pen up to safe Z)
\"\"\"

layer_start = "(--- layer {{layer_id}} ---)\\n"

segment_first = \"\"\"G0 X{{x:.3f}} Y{{y:.3f}} (rapid to stroke start)
G1 Z{down:.3f} F{z_f} (pen down)
\"\"\"

segment = "G1 X{{x:.3f}} Y{{y:.3f}} F{draw_f}\\n"

line_end = "G1 Z{up:.3f} F{z_f} (pen up)\\n"

document_end = \"\"\"G1 Z{up:.3f} F{z_f} (final pen up)
M30
\"\"\"
"""


def render_preview_profile() -> str:
    """gwrite profile producing parseable per-stroke polylines.

    Per-layer output file, one stroke per line, space-separated x,y pairs:
        x1,y1 x2,y2 x3,y3 ...
        x1,y1 x2,y2 ...

    No vertical flip — coordinates stay in SVG space so the polylines
    overlay directly on the browser canvas.
    """
    return """[gwrite.preview]
unit = "mm"
vertical_flip = false
document_start = ""
layer_start = ""
line_start = ""
segment_first = "{x:.3f},{y:.3f} "
segment = "{x:.3f},{y:.3f} "
line_end = "\\n"
document_end = ""
"""


# ---------- shared pipeline runner ----------

def run_vpype_pipeline(svg_text: str, profile_toml: str, profile_name: str,
                       file_pattern: str, tolerance_mm: float, tmp_dir: Path):
    """Write the SVG + profile to tmp_dir, run vpype with our optimization
    pipeline, and gwrite per-layer files. Returns (list_of_output_files, proc)
    where proc is the completed subprocess (for error inspection).
    """
    svg_path = tmp_dir / "input.svg"
    cfg_path = tmp_dir / "runtime.toml"
    out_dir = tmp_dir / "out"
    out_dir.mkdir(exist_ok=True)

    svg_path.write_text(svg_text, encoding="utf-8")
    cfg_path.write_text(profile_toml, encoding="utf-8")

    out_pattern = str(out_dir / file_pattern)

    cmd = [
        str(VPYPE_EXE),
        "--config", str(cfg_path),
        "read", str(svg_path),
        "linemerge",
        "linesort",
        "linesimplify", "-t", f"{tolerance_mm}mm",
        "forlayer",
            "gwrite", "-p", profile_name, out_pattern,
        "end",
    ]

    proc = subprocess.run(
        cmd, capture_output=True, text=True, cwd=str(tmp_dir), timeout=120,
    )
    return sorted(out_dir.iterdir()), proc, cmd


# ---------- routes ----------

@app.route("/")
def index():
    return send_from_directory(APP_DIR, "index.html")


@app.route("/<path:path>")
def static_proxy(path):
    return send_from_directory(APP_DIR, path)


@app.route("/api/defaults")
def api_defaults():
    return jsonify(DEFAULT_SETTINGS)


@app.route("/api/plot", methods=["POST"])
def api_plot():
    """JSON: { svg, settings } → ZIP of per-layer .gcode files."""
    svg_text, settings, err = _read_payload()
    if err: return err

    tolerance = settings.get("tolerance_mm", DEFAULT_SETTINGS["tolerance_mm"])

    with tempfile.TemporaryDirectory(prefix="penplotter_") as td:
        td = Path(td)
        try:
            files, proc, cmd = run_vpype_pipeline(
                svg_text=svg_text,
                profile_toml=render_gcode_profile(settings),
                profile_name="ddcs_runtime",
                file_pattern="layer_%_lid%_%_name%.gcode",
                tolerance_mm=tolerance,
                tmp_dir=td,
            )
        except subprocess.TimeoutExpired:
            return jsonify({"error": "vpype timed out"}), 504

        if proc.returncode != 0:
            return jsonify({
                "error": "vpype failed",
                "stderr": proc.stderr[-4000:],
                "stdout": proc.stdout[-2000:],
                "cmd": cmd,
            }), 500
        if not files:
            return jsonify({"error": "No G-code produced. Is the SVG empty?"}), 500

        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in files:
                zf.write(f, arcname=f.name)
        buf.seek(0)
        return send_file(buf, mimetype="application/zip",
                         as_attachment=True, download_name="plotter_gcode.zip")


@app.route("/api/preview", methods=["POST"])
def api_preview():
    """JSON: { svg, settings } → JSON of per-layer polylines that match
    exactly what /api/plot will draw. Used by the canvas preview overlay.

    Returns:
        {
          "layers": [
            { "name": "black", "color": "#000000",
              "strokes": [ [[x,y], [x,y], ...], ... ] },
            ...
          ]
        }
    """
    svg_text, settings, err = _read_payload()
    if err: return err

    tolerance = settings.get("tolerance_mm", DEFAULT_SETTINGS["tolerance_mm"])

    with tempfile.TemporaryDirectory(prefix="penplotter_preview_") as td:
        td = Path(td)
        try:
            files, proc, cmd = run_vpype_pipeline(
                svg_text=svg_text,
                profile_toml=render_preview_profile(),
                profile_name="preview",
                # NB: file extension matters only for our parsing; .txt keeps
                # it obvious the contents are plain text, not gcode.
                file_pattern="layer_%_lid%_%_name%.txt",
                tolerance_mm=tolerance,
                tmp_dir=td,
            )
        except subprocess.TimeoutExpired:
            return jsonify({"error": "vpype timed out"}), 504

        if proc.returncode != 0:
            return jsonify({
                "error": "vpype failed",
                "stderr": proc.stderr[-4000:],
                "cmd": cmd,
            }), 500

        layers = []
        # Filename format: layer_<lid>_<name>.txt
        name_re = re.compile(r"^layer_(\d+)_(.+)\.txt$")
        for f in files:
            m = name_re.match(f.name)
            if not m: continue
            lid = int(m.group(1))
            name = m.group(2)
            strokes = _parse_polyline_file(f)
            layers.append({"id": lid, "name": name, "strokes": strokes})

        return jsonify({"layers": layers})


def _read_payload():
    payload = request.get_json(silent=True) or {}
    svg_text = payload.get("svg")
    settings = payload.get("settings") or {}
    if not svg_text or "<svg" not in svg_text:
        return None, None, (jsonify({"error": "Missing or invalid SVG content"}), 400)
    if not VPYPE_EXE.exists():
        return None, None, (jsonify({"error": f"vpype not found at {VPYPE_EXE}"}), 500)
    return svg_text, settings, None


def _parse_polyline_file(path: Path):
    """Each non-empty line is one stroke: "x,y x,y x,y ...". Returns
    list[list[[x,y]]]."""
    strokes = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line: continue
        pts = []
        for tok in line.split():
            try:
                x_s, y_s = tok.split(",")
                pts.append([float(x_s), float(y_s)])
            except ValueError:
                continue
        if len(pts) >= 2:
            strokes.append(pts)
    return strokes


if __name__ == "__main__":
    host = "127.0.0.1"
    port = 5005
    print(f"Pen plotter app on http://{host}:{port}/", file=sys.stderr)
    app.run(host=host, port=port, debug=False)
