// G-code program header — DDCS Expert M350 dialect. Sets mm, absolute,
// XY plane, feed-per-min, lifts the pen to safe Z. Matches the layout
// used by the Fusion DDCS post-processor: parens comments, no G10/G28.

export function header({ penUpZ, zFeed }) {
    return [
        "(--- DDCS pen plotter program ---)",
        "(Generated by pen plotter app)",
        "G21 (mm)",
        "G90 (absolute)",
        "G17 (XY plane)",
        "G94 (feed per min)",
        `G1 Z${penUpZ.toFixed(3)} F${zFeed} (pen up to safe Z)`,
    ].join("\n") + "\n";
}
